# Port to Service Mapping
# 端口服务映射配置

# FTP
21:
  service: ftp
  description: File Transfer Protocol

# SSH
22:
  service: ssh
  description: Secure Shell

# Telnet
23:
  service: telnet
  description: Telnet

# SMTP
25:
  service: smtp
  description: Simple Mail Transfer Protocol

# DNS
53:
  service: dns
  description: Domain Name System

# HTTP
80:
  service: http
  description: Hypertext Transfer Protocol

# POP3
110:
  service: pop3
  description: Post Office Protocol v3

# IMAP
143:
  service: imap
  description: Internet Message Access Protocol

# HTTPS
443:
  service: https
  description: HTTP Secure

# SMB
445:
  service: smb
  description: Server Message Block

# IMAPS
993:
  service: imaps
  description: IMAP over SSL

# POP3S
995:
  service: pop3s
  description: POP3 over SSL

# MSSQL
1433:
  service: mssql
  description: Microsoft SQL Server

# Oracle
1521:
  service: oracle
  description: Oracle Database

# MySQL
3306:
  service: mysql
  description: MySQL Database

# RDP
3389:
  service: rdp
  description: Remote Desktop Protocol

# PostgreSQL
5432:
  service: postgresql
  description: PostgreSQL Database

# VNC
5900:
  service: vnc
  description: Virtual Network Computing

# Redis
6379:
  service: redis
  description: Redis Database

# HTTP Proxy
8080:
  service: http-proxy
  description: HTTP Proxy

# HTTPS Alt
8443:
  service: https-alt
  description: HTTPS Alternative

# MongoDB
27017:
  service: mongodb
  description: MongoDB Database

# Elasticsearch
9200:
  service: elasticsearch
  description: Elasticsearch

# Kibana
5601:
  service: kibana
  description: Kibana

# Zookeeper
2181:
  service: zookeeper
  description: Apache Zookeeper

# Kafka
9092:
  service: kafka
  description: Apache Kafka

# Memcached
11211:
  service: memcached
  description: Memcached

# Docker
2375:
  service: docker
  description: Docker API (unencrypted)

2376:
  service: docker-tls
  description: Docker API (TLS)

# Kubernetes
6443:
  service: kubernetes-api
  description: Kubernetes API Server

# etcd
2379:
  service: etcd
  description: etcd Client

# Consul
8500:
  service: consul
  description: Consul HTTP API

# RabbitMQ
5672:
  service: amqp
  description: RabbitMQ AMQP

15672:
  service: rabbitmq-management
  description: RabbitMQ Management

# LDAP
389:
  service: ldap
  description: LDAP

636:
  service: ldaps
  description: LDAP over SSL

# Samba
139:
  service: netbios-ssn
  description: NetBIOS Session Service

# SNMP
161:
  service: snmp
  description: Simple Network Management Protocol

# NFS
2049:
  service: nfs
  description: Network File System

# Rsync
873:
  service: rsync
  description: Rsync

# Git
9418:
  service: git
  description: Git Protocol

# SVN
3690:
  service: svn
  description: Subversion

# Jenkins
8081:
  service: jenkins
  description: Jenkins CI

# Tomcat AJP
8009:
  service: ajp13
  description: Apache JServ Protocol

# Weblogic
7001:
  service: weblogic
  description: Oracle WebLogic

# JDWP
5005:
  service: jdwp
  description: Java Debug Wire Protocol

# CouchDB
5984:
  service: couchdb
  description: Apache CouchDB

# Cassandra
9042:
  service: cassandra
  description: Apache Cassandra

# InfluxDB
8086:
  service: influxdb
  description: InfluxDB

# Prometheus
9090:
  service: prometheus
  description: Prometheus

# Grafana
3000:
  service: grafana
  description: Grafana
